#!/bin/bash
set -e

source $(dirname $0)/version

ARCH=${ARCH:?"ARCH not set"}
SUFFIX=""
[ "${ARCH}" != "amd64" ] && SUFFIX="_${ARCH}"

cd $(dirname $0)/../package

TAG=${TAG:-${IMAGE_VERSION}${SUFFIX}}
REPO=${REPO:-rancher}

if [ ! -e ../bin/plugin-manager -o ! -e ../bin/oldvethsync ]; then
    ../scripts/build
fi

cp ../bin/plugin-manager ../bin/oldvethsync .

IMAGE=${REPO}/network-manager:${TAG}
docker build -t ${IMAGE} .
echo ${IMAGE} > ../dist/images
echo Built ${IMAGE}
